version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - '3306'
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: access1234
      MINIO_ROOT_PASSWORD: secret1234
    volumes:
      - ./data/minio:/data
    command: server  /data --console-address ":9001"
    # ports:
    #   - 9002:9002
    #   - 9005:9005

volumes:
###> doctrine1/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
